version: 2.1

executors:
  linux: &linux-executor
    docker:
      - image: cimg/base:2020.01
  macos: &macos-executor
    macos:
      xcode: 11.3.0
  windows: win/default


orbs:
  win: circleci/windows@2.4.0
  node: circleci/node@4.5.1

commands:
  npmrc:
    steps:
      - run:
          name: Create .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

  setup_git:
    steps:
      - run:
          name: "Setup git environment"
          command: git config --global core.autocrlf false

  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install

  install_node:
    description: Install nodejs
    parameters:
      os:
        type: executor
      node_version:
        type: string
    steps:
      - when:
          condition:
            or:
              - equal: [ *macos-executor, << parameters.os >> ]
              - equal: [ *linux-executor, << parameters.os >> ]
          steps:
            - node/install:
                node-version: << parameters.node_version >>

      - unless:
          condition:
            or:
              - equal: [ *macos-executor, << parameters.os >> ]
              - equal: [ *linux-executor, << parameters.os >> ]
          steps:
            - run:
                name: Install Node.js << parameters.node_version >>
                command: nvm install << parameters.node_version >>
            - run:
                name: Use Node.js << parameters.node_version >>
                command: nvm use << parameters.node_version >>

jobs:
  lint:
    parameters:
      node_version:
        type: string
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - run:
          name: Run lint
          command: npm run lint

  test:
    parameters:
      os:
        type: executor
      node_version:
        type: string
    executor: << parameters.os >>
    steps:
      - setup_git
      - install_node:
          os: << parameters.os >>
          node_version: << parameters.node_version >>
      - checkout
      - install_deps
      - run:
          name: Run tests
          command: npm test

  release:
    resource_class: small
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - npmrc
      - install_deps
      - run:
          name: Release
          command: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - lint:
          name: lint
          context: nodejs-install
          node_version: "14"
          filters:
            branches:
              ignore:
                - master

      - test:
          matrix:
            parameters:
              os: [linux, macos, windows]
              node_version: ["10.22", "12.18", "14.8"]

      - release:
          name: Release
          context: nodejs-lib-release
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
